#!/usr/bin/env python3
"""
Domain 6 — Limitations, Risks & Hallucination. 31 questions.

BIAS CONTROL: every option is written to a similar length and specificity so the
correct answer is not identifiable as the longest or most detailed option.
"""

Q6 = [
{"q":"Which best defines hallucination in a language model?",
 "opts":["Confident, fluent output that is factually wrong with no signal that anything is amiss",
         "A visible error message that appears whenever the model cannot answer a question",
         "Output that the model declines to produce on safety, policy or ethical grounds",
         "Text that starts repeating itself once the context window has been exceeded"],
 "ans":0,
 "exp":"Syllabus 6.1 defines hallucination as confident, fluent output that is factually wrong, with no signal that anything is amiss. The absence of any warning cue is what makes it dangerous, because the text looks exactly as trustworthy as correct text.",
 "why":["Correct. This is the syllabus 6.1 definition, and the missing warning signal is the key feature.",
        "Hallucination is not an error state, and the model produces plausible text and presents it normally.",
        "Refusals are a safety behaviour rather than hallucination, and they are visible rather than silent.",
        "Repetition is a separate context-window effect, while hallucination concerns fabricated or wrong content."]},

{"q":"Why does the syllabus describe hallucination as inherent to how language models work?",
 "opts":["Models generate likely next tokens, so fluent text can appear without any factual grounding",
         "Models are deliberately engineered to mislead their users on a small percentage of occasions",
         "Models eventually run out of stored facts and invent replacements in order to keep responding",
         "Models simply reproduce errors that were present in the training data they were built from"],
 "ans":0,
 "exp":"Syllabus 6.1 links hallucination to the mechanism described in 2.2, namely next-token prediction producing likely continuations. Nothing in that process checks whether a continuation is true, so fabrication is a natural consequence rather than an occasional bug.",
 "why":["Correct. Generation by likelihood has no built-in truth check, which is why the flaw is structural.",
        "There is no designed intent to mislead, and the behaviour emerges from how the model generates text.",
        "Models do not run out of storage mid-response, since they generate tokens regardless of knowledge.",
        "Training-data errors are one source of wrongness, but hallucination arises from generation itself."]},

{"q":"A model produces a fluent, confident answer containing three specific-looking statistics. What is the syllabus position?",
 "opts":["Figures and citations are high-risk elements that must be verified at their original source",
         "Statistics from a modern model can be trusted whenever the surrounding answer reads well",
         "Numbers are inherently safer than prose because they look precise and specific to readers",
         "The model will reliably flag any statistic that it is genuinely unsure about when it writes"],
 "ans":0,
 "exp":"Syllabus 6.3 identifies citations, statistics and quotes as high-risk, and requires confirming important information at its original source. Syllabus 6.2 warns specifically that fabricated statistics appear authoritative.",
 "why":["Correct. Statistics are named in 6.3 as high-risk and require verification at source before use.",
        "Fluency is precisely the misleading signal that makes hallucination dangerous, as 6.1 warns.",
        "Precision of form says nothing about accuracy, since fabricated figures look precise by design.",
        "According to 6.1 there is no signal when something is wrong, so self-flagging cannot be relied on."]},

{"q":"What should you do about a citation produced by an AI tool?",
 "opts":["Confirm it exists and confirm that it actually supports the proposition it is attached to",
         "Assume it is valid provided that the author name and the year both look familiar to you",
         "Check it against the response that a second and different AI tool gives to the same question",
         "Accept it provided the citation appears in a plausible and correctly formatted reference style"],
 "ans":0,
 "exp":"Syllabus 6.3 requires confirming important information at its original source, and 6.4 specifies cross-checking against primary sources rather than another AI. A citation can exist yet not support the claim attributed to it, so both existence and support must be checked.",
 "why":["Correct. Both conditions matter, since the source must exist and must substantiate the stated proposition.",
        "Familiar-looking author names and years are exactly the surface plausibility that fabrication exploits.",
        "Syllabus 6.4 explicitly rules this out, because cross-checking against another AI is not verification.",
        "Correct formatting is trivial to generate and therefore proves nothing about existence or accuracy."]},

{"q":"Cross-checking an AI answer against a second AI tool. What does the syllabus say?",
 "opts":["It is not verification, and you should check against primary sources instead",
         "It is the most reliable and convenient verification method currently available",
         "It is a mandatory step for any output that will be used in a high-stakes setting",
         "It is acceptable only where both models come from the same underlying provider"],
 "ans":0,
 "exp":"Syllabus 6.4 is explicit that you should cross-check against primary sources rather than another AI. Two models drawing on similar patterns can produce the same confident error, so agreement between them is not evidence of truth.",
 "why":["Correct. Syllabus 6.4 rules out AI-to-AI checking and directs you to primary sources instead.",
        "It offers no independent evidence of truth, so it cannot be considered the most reliable method.",
        "It is not required, and it is specifically discouraged as a substitute for checking sources.",
        "Provider similarity makes agreement even weaker as evidence of accuracy rather than stronger."]},

{"q":"What is the effect of the knowledge cut-off on time-sensitive questions?",
 "opts":["The base model cannot know later events, so such answers are unreliable without live sources",
         "The model silently updates itself as new information becomes available online each day",
         "The model automatically warns you whenever a question postdates its own training date",
         "The model becomes noticeably less confident in its answers but remains broadly accurate"],
 "ans":0,
 "exp":"Syllabus 2.4 and 6.2 establish that a base model has no knowledge of events after its training date, so time-sensitive questions are unreliable from the base model alone. Some applications add live search, but the base model itself remains frozen.",
 "why":["Correct. The training date is a hard boundary, so anything after it must come from an external source.",
        "The base model does not update itself by browsing, and only applications with added search supply current data.",
        "There is no reliable warning, which is exactly why this limitation must be known in advance.",
        "Accuracy on post-cut-off events is not merely reduced but ungrounded, so the model may invent details."]},

{"q":"An AI tool claims to be 'hallucination-free' because it uses retrieval. How should you treat that claim?",
 "opts":["Sceptically, because retrieval reduces error but does not actually remove it",
         "As reliable, because retrieval grounds every answer in a set of real documents",
         "As reliable for citations specifically, even if other content needs checking",
         "As a firm vendor commitment that the tool will reimburse you for any error"],
 "ans":0,
 "exp":"Syllabus 3.3 states plainly that RAG improves freshness and grounding but reduces rather than removes error. Research into retrieval-based legal research tools marketed as hallucination-free found continued hallucination across a substantial proportion of queries.",
 "why":["Correct. This restates syllabus 3.3 and matches the evidence that retrieval is not a panacea.",
        "Retrieval improves grounding but cannot guarantee that every generated claim traces to a retrieved source.",
        "Citation accuracy is itself a documented weakness of retrieval-based tools rather than a strength.",
        "The syllabus excludes commercial product evaluation, since the certification is deliberately vendor-neutral."]},

{"q":"Why does 'it looked completely convincing' fail as a defence for publishing AI errors?",
 "opts":["Fluency is not a signal of accuracy, and the human remains fully accountable for it",
         "Because publishing any content that was produced with AI assistance is always prohibited",
         "Because text that appears convincing is statistically more likely to contain errors in it",
         "Because the model should have flagged its own uncertainty clearly before you published"],
 "ans":0,
 "exp":"Syllabus 6.1 explains that hallucination carries no warning signal, and syllabus 8.2 states that 'the AI did it' is not a defence. Convincing presentation is precisely the failure mode, so it cannot also serve as the excuse.",
 "why":["Correct. The absence of a warning plus retained human accountability means plausibility excuses nothing.",
        "The syllabus does not ban publishing AI-assisted content, and it requires verification and sometimes disclosure.",
        "Convincing text is not statistically more likely to be wrong, and the point is that it tells you nothing.",
        "According to 6.1 there is no reliable self-flagging, so this cannot be the standard you rely on."]},

{"q":"Which set names the mandated verification contexts from syllabus 6.5?",
 "opts":["Legal, medical, financial, safety, HR or people decisions, and anything published externally",
         "Legal and medical work only, since these are the two fields where errors cause direct harm",
         "Any task that involves reading and combining more than one document into a single output",
         "Only work that will be reviewed by senior management or an external regulatory authority"],
 "ans":0,
 "exp":"Syllabus 6.5 lists the contexts where verification is required: legal, medical, financial, safety, HR and people decisions, and anything published externally. These share high stakes and direct impact on people.",
 "why":["Correct. This is the complete 6.5 list, and external publication is included because reach amplifies harm.",
        "Legal and medical are included, but so are financial, safety, HR and externally published material.",
        "Document count does not determine stakes, since a single-document legal memo still needs verification.",
        "Visibility to management is not the criterion, because impact and stakes are what actually matter."]},

{"q":"Which is a practical grounding technique from syllabus 6.4?",
 "opts":["Providing the real source text and instructing the model to answer only from it",
         "Asking the model to be more careful and considered in its general approach",
         "Using a larger model that has more parameters and a longer training history",
         "Rewriting the question so that it is shorter and more tightly focused"],
 "ans":0,
 "exp":"Syllabus 6.4 recommends grounding prompts in real content, asking the model to flag uncertainty, cross-checking against primary sources, and keeping a human in the loop. Supplying the actual source text and constraining the answer to it is grounding in its most direct form.",
 "why":["Correct. Anchoring the answer to supplied text is the clearest and most practical application of grounding.",
        "General carefulness instructions are vague and do not supply any factual anchor for the answer.",
        "Model size is not a grounding technique, and the syllabus stays neutral about capability claims.",
        "Shortening a question does not connect it to a source, since grounding is about supplying evidence."]},

{"q":"How does an AI tool differ from a search engine when answering a factual question?",
 "opts":["The tool generates text that may not trace to a real source, while search returns indexed items",
         "The tool is always more accurate because it genuinely understands the meaning behind the query",
         "The tool automatically cites its sources and those citations can therefore be relied upon",
         "There is no meaningful practical difference between the two for factual questions of this kind"],
 "ans":0,
 "exp":"Syllabus 6.3 draws the distinction between generated content and sourced content. A search engine returns actual indexed material you can open, whereas a generative tool produces text, and whether it corresponds to a real source must be checked.",
 "why":["Correct. Generated content is not the same as sourced content, which is the crux of syllabus 6.3.",
        "Understanding meaning does not make the output traceable to a real and checkable source.",
        "Citations can be fabricated, which makes them one of the highest-risk outputs named in 6.3.",
        "The difference is material and is exactly why the verification obligations differ between them."]},

{"q":"What role does keeping 'a human in the loop' play?",
 "opts":["A person reviews the output and takes responsibility before it is used or acted upon",
         "A person types the prompt into the tool on the model's behalf to speed up the process",
         "A person monitors the model's electricity consumption and hardware resource usage",
         "A person approves the training data that the underlying model was originally built on"],
 "ans":0,
 "exp":"Syllabus 6.4 names keeping a human in the loop as a risk-reduction measure, and 8.3 sets out the principle that AI proposes while a person decides and owns the outcome. The human is a decision point rather than an operator.",
 "why":["Correct. Oversight means a person reviews and owns the result before it has any real effect.",
        "Prompt entry is a purely mechanical task that confers no oversight or accountability whatsoever.",
        "Infrastructure monitoring is unrelated to the accountability that genuine oversight provides.",
        "Training-data approval is not what in-the-loop oversight means in this particular syllabus."]},

{"q":"Why does the syllabus call hallucination a professional risk rather than a technical curiosity?",
 "opts":["Unverified AI content has led to real sanctions, retractions and reputational damage",
         "Because hallucination consumes excessive computing resources during normal operation",
         "Because hallucination noticeably slows down the model's response times for all its users",
         "Because correcting it requires expensive specialist intervention from qualified engineers"],
 "ans":0,
 "exp":"Real-world consequences are documented, including court sanctions against lawyers who filed AI-fabricated citations, adverse findings against tribunals and authorities relying on AI-generated material, and research-misconduct exposure for published articles containing hallucinated references. That is why verification is framed as a professional duty.",
 "why":["Correct. The harm is professional and documented, covering sanctions, retractions and damaged standing.",
        "Computing cost is not the concern that the syllabus raises anywhere in this domain.",
        "Response time is unrelated to the professional risk that the syllabus is describing here.",
        "The remedy is an ordinary professional habit of verifying at source rather than specialist intervention."]},

{"q":"What does 'fluency does not guarantee accuracy' mean in practice?",
 "opts":["Well-written output can still be wrong, so prose quality is not evidence of correctness",
         "Only poorly written output needs to be checked, since fluent output is reliable by nature",
         "Fluent output is usually wrong, so it should generally be treated as suspect by default",
         "Accuracy only really matters in formal writing such as reports and academic publications"],
 "ans":0,
 "exp":"Syllabus 2.2 makes this point directly in the context of how language models generate text, and 6.1 repeats it. Because the model optimises for likely continuations, it can produce polished prose around entirely false content.",
 "why":["Correct. Prose quality and factual accuracy are independent, so good writing cannot proxy for truth.",
        "All output should be assessed, since prose quality is not a filter for what needs checking.",
        "Fluent output is often correct, and the real point is that fluency alone tells you nothing either way.",
        "Accuracy matters in all contexts, although the stakes and consequences differ between domains."]},

{"q":"A vendor says its AI 'never makes things up because it only uses your documents'. What is the sound professional response?",
 "opts":["Ask what happens when the supplied documents do not contain an answer to the question",
         "Accept it, because a system grounded in your own documents cannot fabricate content",
         "Accept it provided the tool also offers a very large context window for long documents",
         "Refuse to use any retrieval-based tool at all, since none of them can be fully trusted"],
 "ans":0,
 "exp":"Syllabus 3.3 warns that RAG reduces rather than removes error. A model constrained to documents still has to compose an answer, and when the source is silent it may bridge the gap, which is where fabrication returns.",
 "why":["Correct. The failure mode appears precisely where the source material is silent or ambiguous.",
        "No grounding system eliminates fabrication, as 3.3 and the retrieval-tool evidence both show.",
        "Context-window size does not guarantee that answers are traceable to the supplied material.",
        "Retrieval-based tools are useful and the syllabus supports using them with verification, not refusing them."]},

{"q":"Which is the best example of a fabricated statistic risk?",
 "opts":["A precise-sounding figure attributed to a named report that does not contain it",
         "A rounded estimate that the model itself labels as approximate and uncertain",
         "A figure that the model calculates directly from numbers you supplied to it",
         "A statistic that the model explicitly says it is not confident about providing"],
 "ans":0,
 "exp":"Syllabus 6.2 warns that fabricated statistics, citations, quotes and case studies appear authoritative. Specificity plus a plausible attribution is exactly the combination that defeats casual review, which is why source checking is mandatory.",
 "why":["Correct. Specificity and a credible attribution are what make a fabricated figure genuinely dangerous.",
        "A labelled approximation is honest about its limits and is not presented as a sourced fact.",
        "A calculation from supplied numbers is traceable back to your own inputs and can be checked.",
        "An explicit statement of uncertainty is the opposite of the confident fabrication the syllabus describes."]},

{"q":"When a summary of a high-stakes document is being prepared with AI, what must happen?",
 "opts":["The original must be read, because summaries can omit critical detail",
         "The summary is sufficient provided it is well structured and clearly laid out",
         "A second AI summary can reasonably substitute for reading the original document",
         "Only the executive summary section of the original needs to be checked over"],
 "ans":0,
 "exp":"Syllabus 5.2 names the limitation that summaries can omit critical detail, and requires reading the original for high-stakes documents. Compression always involves judgement about what to drop, and that judgement may discard what matters most to you.",
 "why":["Correct. For high-stakes material the original is the authority and the summary is only an aid.",
        "Good structure does not prevent omission, since formatting says nothing about completeness.",
        "Two summaries can drop the same material, and neither of them is the authoritative document.",
        "Checking one section does not establish that nothing important was omitted from the rest."]},

{"q":"Which behaviour best matches 'verification at the original source'?",
 "opts":["Opening the cited document itself and reading the relevant passage",
         "Asking the model to confirm the accuracy of its own earlier answer",
         "Checking that the citation's web address resolves to a live page",
         "Searching for the claim to see whether other AI answers repeat it"],
 "ans":0,
 "exp":"Syllabus 6.3 requires confirming important information at its original source, and 6.4 directs cross-checking against primary sources. Reading the actual passage is the only method that establishes both existence and support.",
 "why":["Correct. Reading the source passage confirms the document exists and says what was claimed.",
        "Self-confirmation is not independent evidence and may simply repeat the original error.",
        "A resolving address does not prove the source supports the claim, and fabricated citations can point at irrelevant pages.",
        "Recurrence across AI answers may reflect shared training patterns rather than an underlying source."]},

{"q":"What is the significance of the documented court sanctions involving AI citations?",
 "opts":["They show that unverified AI content carries real professional consequences",
         "They show that AI is fundamentally unsuitable for all professional writing tasks",
         "They show that only lawyers and legal professionals are affected by hallucination",
         "They show that courts have now banned the use of AI in legal drafting entirely"],
 "ans":0,
 "exp":"Sanctions, referral to disciplinary authorities and orders to pay opposing costs demonstrate that the verification duty is enforceable rather than merely advisory. This is what turns syllabus 6.5 from guidance into professional obligation.",
 "why":["Correct. The cases establish that failing to verify AI output has enforceable professional consequences.",
        "AI remains useful for drafting, so the lesson concerns verification rather than blanket prohibition.",
        "The documented pattern spans courts, tribunals, authorities and research publication across many countries.",
        "Courts have increasingly required disclosure and verification rather than imposing a total ban."]},

{"q":"Which is the most reliable way to check whether an AI claim about a regulation is correct?",
 "opts":["Read the regulation on the official publisher's website for that jurisdiction",
         "Ask the AI model to explain its reasoning about the regulation in more detail",
         "Ask a completely different AI model the very same question and compare replies",
         "Check whether the answer the model gave is internally consistent and coherent"],
 "ans":0,
 "exp":"Syllabus 6.3 and 6.4 both point to the original source. For a regulation, the authoritative text is published by the issuing body, and only that text settles what the regulation actually says.",
 "why":["Correct. The official published text is the definitive authority for what a regulation provides.",
        "More detailed reasoning may simply elaborate a fabrication with greater fluency and confidence.",
        "A second model can reproduce the same error, which syllabus 6.4 explicitly anticipates.",
        "An answer can be internally consistent and still be factually wrong in its substantive claims."]},

{"q":"Why is a fabricated quote particularly dangerous in professional work?",
 "opts":["It attaches a real person's name to words they never actually said",
         "It is usually much longer than a fabricated statistic would be",
         "It is considerably harder for the model to generate than other text",
         "It only causes problems in social media and public commentary posts"],
 "ans":0,
 "exp":"Syllabus 6.3 identifies quotes as high-risk alongside citations and statistics. A fabricated quote does two kinds of damage, since the claim itself may be false and a named individual is misrepresented, which can carry its own professional and reputational consequences.",
 "why":["Correct. Misattribution harms a real person and compounds the accuracy problem with a reputational one.",
        "Length is irrelevant to the risk, since the harm comes from the false attribution itself.",
        "Generating plausible dialogue is well within a language model's ordinary capability.",
        "Fabricated quotes are equally dangerous in reports, briefings, board papers and academic work."]},

{"q":"What does 'AI proposes while a person decides' require in practice?",
 "opts":["A named human reviews and approves the output before it takes effect",
         "The AI must state its own confidence level clearly before proceeding further",
         "The task must be small enough for one single person to check it all through",
         "The AI must be switched off completely during the final review stage"],
 "ans":0,
 "exp":"Syllabus 8.3 states this principle directly, and 6.4 requires keeping a human in the loop. In practice it means that a specific, identifiable person accepts responsibility before the output is acted on or published.",
 "why":["Correct. Oversight requires an accountable person who approves before any consequences follow.",
        "Confidence statements are not reliable signals, as syllabus 6.1 makes clear to candidates.",
        "Task size does not determine accountability, since large tasks can still have a named approver.",
        "The tool need not be switched off, but a person must own the eventual decision."]},

{"q":"Which is the correct handling of an AI-generated case study you want to use in a client proposal?",
 "opts":["Verify the events actually occurred and replace it if it cannot be substantiated",
         "Use it provided it is plausible and reads well as a piece of professional writing",
         "Use it but add the word illustrative somewhere near the case study text",
         "Use it provided that the client is unlikely to check the details for themselves"],
 "ans":0,
 "exp":"Syllabus 6.2 names fabricated case studies alongside statistics and citations as appearing authoritative. Since 6.5 covers anything published externally and client-facing work is high-stakes, an unverifiable case study must be replaced rather than glossed.",
 "why":["Correct. If the events cannot be substantiated then the case study is fabricated and must not be used.",
        "Plausibility is the exact property that makes fabrication dangerous, as syllabus 6.1 explains.",
        "Illustrative does not fix a fabricated claim presented as real, and in client work it may itself mislead.",
        "The likelihood of detection is irrelevant to the question of whether the claim is actually true."]},

{"q":"What is the relationship between the knowledge cut-off and fabricated content?",
 "opts":["Out-of-date knowledge can lead the model to invent plausible detail rather than admit ignorance",
         "A knowledge cut-off only affects the model's response speed and not its factual accuracy",
         "The presence of a knowledge cut-off actually prevents fabrication from occurring at all",
         "Fabrication occurs only on topics that postdate the model's training cut-off date"],
 "ans":0,
 "exp":"Syllabus 6.2 explicitly links stale information to fabrication, since out-of-date output arises from the knowledge cut-off and fabricated statistics and citations appear authoritative. The model tends to answer rather than decline, so gaps get filled with invention.",
 "why":["Correct. Stale knowledge plus a tendency to answer produces confident invention where knowledge runs out.",
        "The cut-off affects what the model knows rather than how quickly it responds to questions.",
        "A cut-off is a boundary on knowledge and not a safeguard against fabrication in any form.",
        "Fabrication is not limited to post-cut-off events and also affects the model's own trained knowledge."]},

{"q":"Which instruction is most useful for surfacing uncertainty?",
 "opts":["If the sources I have given do not answer this, say so rather than inferring an answer",
         "Please be as accurate as you possibly can be in everything that you write for me here",
         "Do not make any mistakes at all in the response that you provide for me this time",
         "Double-check all of your work carefully before you reply to me with the final answer"],
 "ans":0,
 "exp":"Syllabus 6.4 recommends asking the model to flag uncertainty. A specific instruction that identifies the acceptable outcome, namely saying that the supplied material does not answer the question, is far more actionable than a general plea for care.",
 "why":["Correct. Naming the permitted response gives the model a clear alternative to guessing at an answer.",
        "A general wish for accuracy gives the model no mechanism for revealing genuine doubt to you.",
        "Do not make mistakes is unactionable and provides no route for the model to admit a knowledge gap.",
        "Instructions to self-check do not establish any external anchor that could confirm correctness."]},

{"q":"Why is 'the tool said it' insufficient as an audit trail?",
 "opts":["Output must be traceable to a verifiable source, not merely to the tool that produced it",
         "Because AI tools generally do not keep detailed logs of the responses they generate",
         "Because audit trails only really matter in the financial services and accounting sectors",
         "Because the same tool cannot reliably reproduce the same answer on two separate occasions"],
 "ans":0,
 "exp":"Syllabus 6.3 establishes that generated content is not sourced content. An audit trail requires tracing a claim back to an authoritative source, and pointing at the model that produced it establishes only who generated the text, not whether it is true.",
 "why":["Correct. Traceability requires reaching an authoritative source, which the tool itself is not.",
        "Logging is a separate issue, and even a perfect log of a fabricated claim proves nothing about truth.",
        "Verification obligations span legal, medical, financial, safety, HR and published contexts rather than finance alone.",
        "Reproducibility is a variability question at syllabus 2.5 and not the reason an audit trail is required."]},

{"q":"A model gives two different answers to the same factual question on two occasions. What does this indicate?",
 "opts":["Generation involves sampling, so output varies, and variation signals fragility",
         "One of the two answers given must be the correct one of the pair",
         "The second answer is the improved and more reliable of the two replies",
         "The model has learned from the first answer and adjusted its response"],
 "ans":0,
 "exp":"Syllabus 2.5 explains that identical prompts can produce different answers because of sampling and the temperature setting. When a factual claim changes between runs, that instability is a warning that the detail is not securely grounded.",
 "why":["Correct. Variability is expected from sampling, and it is a useful signal that a fact needs checking.",
        "Both answers could be wrong, so variation between them does not imply that one is right.",
        "Later generations are not refinements, and the model does not improve unless you explicitly correct it.",
        "The model does not update its internal weights based on the content of your conversation."]},

{"q":"Which habit most directly reduces the risk of publishing an AI error?",
 "opts":["Applying a fixed verification checklist to names, figures, dates, quotes and citations",
         "Using the most expensive and most recently released model that is available to you",
         "Reading the generated output through carefully two separate times before you send it",
         "Keeping all of your prompts very short and tightly focused on a single small point"],
 "ans":0,
 "exp":"Syllabus 5.5 lists exactly this set, namely facts, figures, dates, names, quotes and citations, as elements to verify before acting on or sharing output. A checklist makes the duty consistent rather than dependent on how convincing the text felt.",
 "why":["Correct. A fixed checklist targets the named high-risk elements and removes reliance on impressions.",
        "Model cost is not a guarantee of accuracy, and the syllabus is deliberately vendor-neutral.",
        "Re-reading catches typographical slips but not fabrications that read perfectly well on the page.",
        "Prompt length is unrelated to the verification duty that applies to the finished output."]},

{"q":"What is the syllabus position on using AI output in a document that will be published externally?",
 "opts":["Verification is mandatory, and disclosure is required where AI substantially generated the content",
         "Publication is prohibited unless a qualified legal specialist has reviewed the document first",
         "No verification is needed provided that a human being edited and tidied up the final text",
         "Only the statistics within the document need to be checked carefully before publication"],
 "ans":0,
 "exp":"Syllabus 6.5 includes anything published externally among the mandated verification contexts, and 8.4 requires disclosure where AI substantially generated the content or where non-disclosure would mislead. Editing improves text but does not make it verified.",
 "why":["Correct. External publication triggers both the verification duty and the disclosure question.",
        "The syllabus excludes legal interpretation, and its remedy is verification with appropriate disclosure.",
        "Editing is not verification, since an editor may smooth fabricated prose without spotting the fabrication.",
        "Citations, quotes and names carry the same risk as statistics and must also be checked."]},

{"q":"Why does the syllabus pair hallucination with critical evaluation as a core competency?",
 "opts":["Because output must be assessed on evidence rather than plausibility before it is trusted",
         "Because all AI output should generally be distrusted as a matter of sensible default policy",
         "Because automated evaluation tools can now reliably detect hallucinations without human help",
         "Because critical evaluation of output removes the need to check against original sources"],
 "ans":0,
 "exp":"Domain 6 is introduced as critical evaluation and verification as a core professional competency. The pairing reflects that hallucination cannot be detected from the output alone, so the professional habit is to evaluate against evidence.",
 "why":["Correct. The competency is disciplined evidence-based assessment of output before relying on it.",
        "The syllabus is not generally distrustful of AI, and it requires appropriate and verified use.",
        "No automated detector reliably identifies hallucination, which is why human verification is required.",
        "Critical evaluation directs you towards source checking and does not substitute for it."]},

{"q":"A colleague says hallucination will disappear as models improve. What is the best-informed response?",
 "opts":["Fabrication has not declined consistently across generations, so verification remains essential",
         "That is correct, so verification can reasonably be relaxed for the very newest models available",
         "Hallucination is actually increasing steadily in every measurable dimension across all models",
         "Hallucination only ever affects older or smaller models and not the current generation of tools"],
 "ans":0,
 "exp":"Research benchmarking fabricated legal citations across eight successive model generations found that hallucination rates were not consistently decreasing, and that newer models produced more citations per document from less canonical sources, which increases the verification burden. The trend is not self-correcting.",
 "why":["Correct. The evidence shows no consistent decline, and the verification burden has grown rather than shrunk.",
        "Assuming improvement and relaxing checks is exactly the behaviour that the evidence warns against.",
        "The finding is that rates are not consistently decreasing, rather than that they are rising in every measure.",
        "Hallucination affects current models, including some marketed as grounding-based and hallucination-free."]},
]
