#!/usr/bin/env python3
"""
Domain 4 — Prompt Engineering Fundamentals. 31 questions.

BIAS CONTROL: every option is written to a similar length and level of
specificity so the correct answer is NOT identifiable as the longest or most
detailed. See _check_bias.py for the audit.
"""

Q4 = [
{"q":"A prompt is built from four components. Which set names all four?",
 "opts":["Task, context, format and constraints",
         "Subject, tone, length and language register",
         "Role, model, temperature and token budget",
         "Question, example, answer and final review"],
 "ans":0,
 "exp":"Syllabus 4.1 defines exactly four components: task (what you want done), context (background the model needs), format (how the output should be shaped) and constraints (the limits it must respect). These four are the backbone of the syllabus prompting model.",
 "why":["Correct. Task, context, format and constraints is the syllabus 4.1 set, and the checklist to run every prompt against.",
        "These are real prompt qualities, but not the four components the syllabus defines; they sit inside format and constraints.",
        "This mixes concepts: role is syllabus 4.2, while model and temperature are Domain 2 settings rather than prompt components.",
        "This describes a question-and-answer cycle rather than the four-component anatomy of a single prompt."]},

{"q":"You write: 'Summarise this report. It is for our board. Keep it to one page. Use short paragraphs and no jargon.' Which component is 'for our board'?",
 "opts":["Context","Format","Constraints","Task"],
 "ans":0,
 "exp":"Naming the audience supplies the background that shapes register and depth, which syllabus 4.2 treats as context. The task is 'summarise'; the format is one page and short paragraphs; the constraints are no jargon.",
 "why":["Correct. The audience tells the model what background to assume and how formal to be, which is context.",
        "Format governs the shape of the output such as one page and short paragraphs, not who will read it.",
        "A constraint is a limit or prohibition, so 'no jargon' is the constraint here rather than 'for our board'.",
        "The task is the action requested, 'summarise this report', while the audience is separate information."]},

{"q":"What does assigning a role, such as 'act as a critical reviewer', actually do?",
 "opts":["It shapes the register, depth and emphasis of the output",
         "It gives the model real domain expertise it otherwise lacks",
         "It guarantees the output will be factually accurate",
         "It unlocks a hidden specialist mode inside the model"],
 "ans":0,
 "exp":"Syllabus 4.2: assigning a role or persona shapes the register and depth of output, and naming the audience does the same for framing. A role steers style, vocabulary and what the model foregrounds; it does not add knowledge or verify anything.",
 "why":["Correct. The role is a framing instruction that changes tone, depth and what gets emphasised in the reply.",
        "A role is only a text instruction, so it cannot grant knowledge the model was never trained on.",
        "No role assignment makes output accurate, and syllabus 2.2 still applies in full.",
        "There is no hidden privileged mode; the role changes how the same model responds and nothing more."]},

{"q":"Which describes few-shot prompting?",
 "opts":["Supplying one or more worked examples to calibrate style and format",
         "Asking the same question several times and keeping the best reply",
         "Breaking a long task into many separate chat sessions over time",
         "Giving the model several attempts so it can correct its own work"],
 "ans":0,
 "exp":"Syllabus 4.3: few-shot prompting uses one or more examples to calibrate style, format and tone. Zero-shot gives no examples; few-shot gives some. The examples teach the pattern you want.",
 "why":["Correct. Examples demonstrate the pattern, which is far more reliable than describing it in the abstract.",
        "Repeating a question is not few-shot prompting; that is re-running a prompt hoping for variation.",
        "Splitting work across sessions relates to the context window at syllabus 2.3, not to few-shot prompting.",
        "Self-correction attempts are iterative refinement at syllabus 4.5, a different technique entirely."]},

{"q":"When is few-shot prompting most worth the extra effort?",
 "opts":["When you need a very specific format, tone or pattern consistently",
         "When the question is a straightforward factual lookup of one item",
         "When you want a short and quick answer to a simple closed question",
         "When the task is fully described by one clear and unambiguous sentence"],
 "ans":0,
 "exp":"Examples earn their cost when the requirement is hard to state in words but easy to show, such as a house style, a table layout or a particular tone. If the instruction is already unambiguous, examples add length without adding calibration.",
 "why":["Correct. Examples are most valuable when the pattern is easier to demonstrate than to describe in words.",
        "A factual lookup needs no style calibration, so examples would only consume context window space.",
        "A short answer needs less shaping, which means examples usually add very little value here.",
        "If one sentence fully specifies the task then the prompt is already clear and examples are redundant."]},

{"q":"Which prompt best requests structured output?",
 "opts":["Return a table with columns: Risk, Likelihood, Impact, Mitigation",
         "Please be organised, methodical and clear in your written response",
         "Write about the identified risks in a professional and readable way",
         "Give me your best and most considered thoughts on the risks involved"],
 "ans":0,
 "exp":"Syllabus 4.4: requesting structured output means naming the structure, including tables, headed sections and defined fields. Specifying the columns makes the shape unambiguous and directly checkable.",
 "why":["Correct. Naming the exact columns gives an unambiguous, verifiable output structure to work against.",
        "Being organised is an aspiration rather than a specification, so the model must guess the structure.",
        "Professional and readable sets tone but says nothing about structure, so the output shape stays unpredictable.",
        "This asks for considered opinions with no format instruction at all, leaving structure to the model."]},

{"q":"What is task decomposition in prompting?",
 "opts":["Breaking a complex task into ordered steps and asking for them in sequence",
         "Shortening the prompt so that it comfortably fits the context window",
         "Asking the model to answer faster by generating fewer output tokens",
         "Removing constraints so that the model has more freedom to respond"],
 "ans":0,
 "exp":"Syllabus 4.4: decompose a complex task into ordered steps, and ask for a plan or reasoning where useful. Decomposition makes the work tractable and the reasoning inspectable.",
 "why":["Correct. Ordered steps turn one large ambiguous request into a sequence of checkable ones.",
        "Trimming a prompt is a context-window technique at syllabus 2.3 rather than decomposition.",
        "Token efficiency is a cost and context concern and has nothing to do with decomposing a task.",
        "Removing constraints loosens the prompt, whereas decomposition adds structure rather than removing it."]},

{"q":"Your first output is broadly right but too formal. What is the correct next move?",
 "opts":["Give a specific corrective follow-up naming the change you want",
         "Start a brand-new chat and rewrite the prompt from the beginning",
         "Accept the output as it stands, since the actual content is right",
         "Add further constraints to a fresh copy of the original prompt"],
 "ans":0,
 "exp":"Syllabus 4.5 treats the first output as a draft and refinement as a conversation that builds on previous responses. A specific correction such as 'make it warmer and less formal, but keep the structure' is the efficient move.",
 "why":["Correct. A targeted follow-up preserves what worked and fixes only the part that did not.",
        "Restarting throws away the working draft along with the context that produced it.",
        "Accepting the wrong tone means the output goes out unfit for purpose when one line would fix it.",
        "Rewriting in a fresh chat loses the draft and may add constraints that you do not actually need."]},

{"q":"Which is a 'one-and-done' prompting fault?",
 "opts":["Accepting the very first output without any refinement at all",
         "Sending a large number of follow-up corrections to the model",
         "Providing a single worked example of the format that you want",
         "Naming the intended audience clearly within the prompt itself"],
 "ans":0,
 "exp":"Syllabus 4.6 lists one-and-done prompts among the common faults. Treating the initial response as final wastes the model's ability to improve through correction, so iterative refinement at 4.5 is exactly what gets skipped.",
 "why":["Correct. One-and-done means treating a draft as a finished product and never refining it.",
        "Refining thoroughly is the recommended practice rather than a fault, and 4.5 encourages correction.",
        "Supplying an example is good practice under few-shot prompting at syllabus 4.3.",
        "Naming the audience is good practice under role and audience at syllabus 4.2."]},

{"q":"A prompt says: 'Look at this and tell me if it's any good and maybe improve it and also check the figures and make it shorter.' What is the main fault?",
 "opts":["It is overloaded, bundling too many separate tasks into one request",
         "It is leading the model toward one particular preferred conclusion",
         "It is unformatted, specifying no required structure for the answer",
         "It is vague about the target audience for the finished output"],
 "ans":0,
 "exp":"Syllabus 4.6 names overloaded prompts as a fault. This one asks for four different things, namely evaluation, improvement, figure checking and shortening, with no order or priority, so no single output can satisfy it well.",
 "why":["Correct. Bundled unordered demands make it impossible for the model to know what to prioritise.",
        "A leading prompt steers toward a desired conclusion, and this prompt does not suggest any answer.",
        "Unformatted is a real fault, but the dominant problem here is that four tasks are crammed together.",
        "Audience vagueness is a fault in itself, but it is not what is principally wrong with this prompt."]},

{"q":"Which prompt is 'leading'?",
 "opts":["Why is remote work clearly better for productivity in most teams?",
         "What are the main arguments for and against remote working?",
         "Summarise the available evidence on remote working productivity.",
         "List the main findings on remote working in the published literature."],
 "ans":0,
 "exp":"A leading prompt embeds the conclusion in the question, so the model is nudged to justify a premise rather than examine it. The phrase 'clearly better' presumes the answer, and syllabus 4.6 lists leading prompts as a fault.",
 "why":["Correct. 'Clearly better' asserts the conclusion, so the model is invited to agree rather than assess.",
        "This asks for both sides of the argument and so does not presuppose any particular answer.",
        "Summarising the evidence is neutral about what that evidence actually shows on balance.",
        "Listing findings asks what the literature says rather than what it ideally ought to say."]},

{"q":"What is the difference between zero-shot and few-shot prompting?",
 "opts":["Zero-shot gives no examples, while few-shot gives one or more examples",
         "Zero-shot uses no role, while few-shot always assigns a specific role",
         "Zero-shot works only for short tasks, while few-shot suits only long ones",
         "Zero-shot needs no prompt, while few-shot needs a system-level message"],
 "ans":0,
 "exp":"Syllabus 4.3 draws this distinction precisely: zero-shot prompting supplies no examples, and few-shot prompting supplies one or more to calibrate style, format and tone. Role and audience at 4.2 are separate and independent techniques.",
 "why":["Correct. The distinguishing feature is purely the presence or absence of worked examples.",
        "Role assignment is independent of shot count, so you can use few-shot without any role at all.",
        "Shot count is unrelated to task length, since short tasks can use examples and long ones may not.",
        "Zero-shot still requires a prompt, which is the whole point; both are prompts that differ in examples."]},

{"q":"Which is the strongest reason to name your audience in a prompt?",
 "opts":["It sets the appropriate register, depth and assumed prior knowledge",
         "It makes the model more factually accurate in what it produces",
         "It automatically shortens the output to a concise useful length",
         "It prevents the model from hallucinating details it cannot know"],
 "ans":0,
 "exp":"Syllabus 4.2: naming the audience shapes the register and depth of the output. Telling the model that the reader is, say, a finance committee means it explains less background and chooses different vocabulary, but it does not change factual reliability.",
 "why":["Correct. Audience information calibrates vocabulary, assumed background and the level of detail given.",
        "Audience framing affects style rather than factual accuracy, and hallucination is a Domain 6 concern.",
        "Audience does not control length, which is a format or constraint instruction you must state separately.",
        "No prompt technique eliminates hallucination, as syllabus 6.1 makes entirely clear."]},

{"q":"You need every output in a consistent corporate house style. Which technique fits best?",
 "opts":["Few-shot prompting using a short example of the house style",
         "Asking for the output to be written in the usual corporate way",
         "Adding the broad constraint to make the writing professional",
         "Raising the temperature setting so the model is more creative"],
 "ans":0,
 "exp":"House style is a pattern that is far easier to show than to describe. Syllabus 4.3 identifies using examples to calibrate style, format and tone as exactly this use case.",
 "why":["Correct. A short worked example conveys a house style more reliably than any written description.",
        "The usual corporate way is undefined, so the model has no way to know your particular house style.",
        "Professional is far too coarse to capture a specific house style and leaves the model guessing.",
        "Higher temperature increases variation, which is the precise opposite of the consistency you want."]},

{"q":"How should you treat the first response to a complex prompt?",
 "opts":["As a draft to be reviewed and refined through follow-up turns",
         "As the final answer provided that it reads fluently and well",
         "As fundamentally unreliable and worth discarding immediately",
         "As a reliable source of facts that can be quoted directly"],
 "ans":0,
 "exp":"Syllabus 4.5 frames checking output as drafting: treat the first result as a draft and refine through specific, corrective follow-ups. Fluency is not a quality signal, and syllabus 2.2 warns that fluent text is not necessarily accurate.",
 "why":["Correct. Draft treatment is the syllabus own framing and it keeps refinement conversational.",
        "Fluency is a poor quality signal, so a polished draft can still contain errors you must catch.",
        "Discarding a broadly correct draft wastes useful work that one follow-up could have refined.",
        "Nothing should be quoted directly without verification, as Domains 5 and 6 make plain."]},

{"q":"Which best explains why prompting should be treated as a conversation?",
 "opts":["Each response gives information you use to write a better next instruction",
         "Longer conversations always cost substantially less than shorter ones",
         "The model permanently remembers your work between separate sessions",
         "The model needs a few exchanges to warm up before it performs well"],
 "ans":0,
 "exp":"Syllabus 4.5: understand prompting as a conversation that builds on previous responses. Each output reveals what worked, and your next instruction can build on it, so the conversation is a feedback loop rather than a nicety.",
 "why":["Correct. The conversation is a feedback loop in which each turn informs the next instruction.",
        "Conversation length relates to context window use at syllabus 2.3 and is not inherently cheaper.",
        "Whether work persists between sessions depends on the application and is not the reason prompting is conversational.",
        "There is no warm-up effect, since a model does not need prior turns to become ready to respond."]},

{"q":"Which single change most reliably fixes a vague prompt?",
 "opts":["State the task, audience and required output format explicitly",
         "Make the prompt much longer and more detailed in a general way",
         "Add the instruction to be accurate and thorough in the answer",
         "Repeat the same request twice within the body of the prompt"],
 "ans":0,
 "exp":"Syllabus 4.1 gives the remedy for vagueness: supply the missing components, which are a clear task, the relevant context, an explicit format and any real constraints. Length is not the answer, since specification is what matters.",
 "why":["Correct. Vagueness is a specification gap, and the four components close it directly.",
        "Longer is not clearer, so padding a vague prompt leaves it vague and consumes context window space.",
        "Being accurate and thorough is an aspiration the model cannot act on and does not improve accuracy.",
        "Repeating a request adds noise and can confuse the instruction rather than resolve the vagueness."]},

{"q":"What does 'decomposing' a task let you do that a single mega-prompt cannot?",
 "opts":["Check and correct each step before it feeds into the next one",
         "Obtain the final answer without performing any verification work",
         "Avoid using the context window at all during the whole process",
         "Guarantee that the final combined output will be entirely correct"],
 "ans":0,
 "exp":"Syllabus 4.4 pairs decomposition with asking for a plan or reasoning where useful. Splitting work into ordered steps gives you intermediate outputs you can review, which is what makes the later steps trustworthy.",
 "why":["Correct. Intermediate steps are checkpoints where errors get caught before they propagate onwards.",
        "Decomposition is not a route to skipping verification, since Domains 5 and 6 still apply in full.",
        "Decomposition still uses the context window, and may use more because each step carries its own text.",
        "No technique guarantees correctness, as the syllabus is explicit that output always requires verification."]},

{"q":"A prompt says: 'Don't be too verbose, but also be comprehensive, and keep it brief but make sure nothing important is left out.' What is the fault?",
 "opts":["The constraints contradict each other so no output can satisfy them",
         "The prompt is far too short to convey what the task actually is",
         "It provides neither a role nor an audience for the requested output",
         "It fails to specify any useful output format for the finished answer"],
 "ans":0,
 "exp":"Syllabus 4.6 covers faults including overloaded and unclear constraint sets. Here comprehensive and brief-with-nothing-left-out pull in opposite directions, so the model must silently pick one and your results become unpredictable.",
 "why":["Correct. Mutually exclusive constraints leave the model to choose arbitrarily, which is unpredictable.",
        "Length of the prompt is not the problem, since the conflict between its requirements is what matters.",
        "Missing role and audience are real gaps but secondary to the contradictory requirements here.",
        "An unstated format is a genuine gap, yet the dominant defect is the contradictory constraints."]},

{"q":"What is the practical benefit of requesting a structured format like a table?",
 "opts":["It makes omissions and errors easier to spot and compare",
         "It makes the model considerably more knowledgeable about the topic",
         "It removes any need for you to verify the content afterwards",
         "It makes the resulting response shorter than an unstructured one"],
 "ans":0,
 "exp":"Syllabus 4.4 recommends structured output such as tables and headed sections. The real payoff is reviewability, since a fixed set of columns shows immediately what is missing or inconsistent, which speeds up your verification step.",
 "why":["Correct. Structure turns review into a checklist, exposing gaps and inconsistencies very quickly.",
        "Format changes presentation rather than knowledge, so the model is no more expert than before.",
        "Structured output still requires verification, because format is not in itself a correctness guarantee.",
        "A table may be longer or shorter depending on content, so brevity is not the point of structuring."]},

{"q":"Which best describes the relationship between prompting and hallucination?",
 "opts":["Better prompting reduces but cannot eliminate hallucination",
         "Better prompting eliminates hallucination completely and reliably",
         "Prompting has no measurable effect on hallucination at all",
         "Hallucination is caused solely by writing excessively long prompts"],
 "ans":0,
 "exp":"Syllabus 6.4 lists grounding prompts in real content as one risk-reduction measure, while 6.1 states hallucination is inherent to how language models work. Prompting is therefore a genuine but partial mitigation rather than a cure.",
 "why":["Correct. Grounding and clarity help materially, but the mechanism still permits confident errors.",
        "No prompt technique removes hallucination, which the syllabus describes as inherent and not a removable bug.",
        "Prompt quality does influence error rates, so claiming zero effect understates the value of better prompting.",
        "Prompt length is not the cause, since hallucination arises from how the model generates text."]},

{"q":"Your prompt reads: 'Summarise the attached 40-page contract in 200 words.' Which component is the 200-word limit?",
 "opts":["Constraint","Task","Context","Role"],
 "ans":0,
 "exp":"Syllabus 4.1 treats constraints as the limits the output must respect. A word limit is a hard boundary, which is exactly a constraint. The task is to summarise, and the context is the attached contract.",
 "why":["Correct. A word limit is a boundary on the output, which is the definition of a constraint.",
        "The task is the action to summarise, while the 200-word figure governs how that task is executed.",
        "Context is background information the model needs, and the contract supplies that rather than the word count.",
        "No role or persona is assigned anywhere in this particular prompt at all."]},

{"q":"Which is the best follow-up to sharpen an output that is correct but disorganised?",
 "opts":["Reorganise the same content under these four headings",
         "Try the whole thing again but do it noticeably better",
         "You made some mistakes, so please fix them for me",
         "Are you completely sure that this version is right"],
 "ans":0,
 "exp":"Syllabus 4.5 requires specific, corrective follow-ups. Naming the exact structure you want is specific, preserves the content you approved, and directly addresses the one problem with the draft.",
 "why":["Correct. Naming the four headings is precise, actionable and keeps the approved content intact.",
        "Better gives no direction at all, so the model must guess what to change and may alter the wrong things.",
        "This implies errors without saying where, risking destructive changes to content that was already right.",
        "Asking for reassurance does not specify a correction and is unlikely to improve the structure."]},

{"q":"Why does the syllabus recommend asking for reasoning or a plan where useful?",
 "opts":["It exposes the model's logic so that you can check it",
         "It makes the model genuinely think like a human being",
         "It guarantees that the final conclusion is entirely correct",
         "It significantly reduces the number of tokens used overall"],
 "ans":0,
 "exp":"Syllabus 4.4 suggests asking for a plan or reasoning where useful. The value is inspectability, since seeing the steps lets you spot the faulty link, which you cannot do from a bare conclusion.",
 "why":["Correct. Visible steps create review points where a wrong assumption becomes apparent to you.",
        "The model does not reason like a human, and the benefit is auditability rather than anthropomorphism.",
        "A visible chain of reasoning can still be wrong or even rationalise a wrong answer, so it guarantees nothing.",
        "Asking for reasoning generally increases output length and therefore token use rather than reducing it."]},

{"q":"What is the key risk of a prompt that is vague about the output format?",
 "opts":["Each run may return a different shape, making output hard to reuse",
         "The model will simply refuse to provide any answer at all",
         "The model will hallucinate considerably more statistics overall",
         "The answer will always come back far too long to be useful"],
 "ans":0,
 "exp":"Syllabus 4.1 treats format as one of the four required components. Without a format instruction the model chooses, and its choice varies between runs, which is why vague prompts produce output you cannot reliably reuse or compare.",
 "why":["Correct. Unspecified format means inconsistent structure that resists reuse and comparison.",
        "Models answer vague format requests happily; they simply pick a shape for themselves.",
        "Hallucination is driven by how models generate text rather than by format specification.",
        "Unformatted output can be short or long, since length is governed by explicit constraints."]},

{"q":"Which combination best matches the four prompt components in: 'Acting as a data analyst, review this sales spreadsheet and give me a table of the three biggest risks.'?",
 "opts":["Task is reviewing the spreadsheet, format is a table, constraints are the three biggest risks",
         "Task is the three biggest risks, format is the spreadsheet, constraints are the data analyst role",
         "Task is the data analyst, format is reviewing, constraints are the three biggest risks listed",
         "Task is the table, format is the data analyst, constraints are the review of the spreadsheet"],
 "ans":0,
 "exp":"The task is the action requested, which is reviewing the spreadsheet. The context is the material supplied, which is the sales data. The format is the requested shape, which is a table. The constraint bounds the answer to the three biggest risks. The analyst role is a layered 4.2 element.",
 "why":["Correct. Each component is correctly identified, with the role recognised as a separate 4.2 layer.",
        "This assigns components to the wrong elements, since the three biggest risks bound the answer rather than form the context.",
        "This mistakes the role for the task, because a data analyst is a persona rather than a requested action.",
        "This labels the role as the format, but a persona is not a structure for presenting an answer."]},

{"q":"When would zero-shot prompting actually be the better choice?",
 "opts":["When the task is simple and a clear instruction is sufficient",
         "When the output must follow a strict and detailed template",
         "When you need a specific house tone across all the output",
         "When the task is complex and very highly patterned throughout"],
 "ans":0,
 "exp":"Syllabus 4.3 asks when to use examples. The answer is when calibration is genuinely needed. For a simple, well-specified task, examples add context-window cost with little benefit, so a clear zero-shot instruction is more efficient.",
 "why":["Correct. Simple clearly specified tasks need no calibration, so zero-shot is leaner and just as effective.",
        "A strict template is precisely where examples help most, which makes zero-shot the weaker choice.",
        "A specific house tone is easier to show than describe, so that is clearly a few-shot case.",
        "Complex patterned tasks benefit most from demonstration, which makes few-shot the better fit."]},

{"q":"An output misses a required element. What is the most efficient correction?",
 "opts":["Point to the specific missing element and ask for it to be added",
         "Rewrite the entire prompt from scratch and open a new chat",
         "Accept the output and simply add the missing element yourself",
         "Ask the model whether anything at all is missing from its answer"],
 "ans":0,
 "exp":"Syllabus 4.6 covers diagnosing and correcting faults, and 4.5 makes refinement specific and corrective. Naming the exact gap keeps the rest of the draft and fixes the problem directly.",
 "why":["Correct. A pointed specific follow-up is the fastest route and preserves the working draft.",
        "Restarting discards approved content along with the context that produced it.",
        "Doing it yourself may be quick once, but it forgoes the refinement the tool is capable of providing.",
        "Asking the model to find its own omissions is unreliable, since it may not recognise the gap."]},

{"q":"Which statement about prompting is most consistent with the syllabus?",
 "opts":["Prompting is the highest-leverage practical skill and is learnable through structure",
         "Prompting is largely an innate talent that only some people happen to possess",
         "Prompting only matters for technical professionals in engineering roles",
         "Prompting is a temporary skill that improving models will soon make obsolete"],
 "ans":0,
 "exp":"Syllabus Domain 4 is introduced as the highest-leverage practical skill, and it is taught as a set of structured techniques including components, roles, examples, decomposition and refinement. That framing makes it learnable and improvable.",
 "why":["Correct. The syllabus frames prompting as the highest-leverage practical skill and presents it as structured technique.",
        "The syllabus teaches prompting as technique with named components, which implies it is learnable rather than innate.",
        "Domain 4 sits in a vendor-neutral non-technical certification aimed at any industry and not only at specialists.",
        "The syllabus presents prompting as core professional competence developed and assessed across the course."]},

{"q":"Which is the best example of an unformatted prompt fault from syllabus 4.6?",
 "opts":["Tell me about our Q3 results",
         "Return a table with four columns covering our Q3 results",
         "Summarise the Q3 results in three bullets written for the board",
         "List the three largest Q3 variances together with their figures"],
 "ans":0,
 "exp":"Syllabus 4.6 lists unformatted prompts as a fault. The bare request states no output shape and no bound, so the model picks the structure, the length and the angle itself, which is exactly the unformatted fault.",
 "why":["Correct. No format and no bound are given, so the output shape is left entirely to the model.",
        "This specifies both the structure and the four columns, so it is well formatted.",
        "This specifies the format of three bullets and names the audience as the board.",
        "This specifies the format of a list and the content of three variances with figures."]},

{"q":"Why does the syllabus treat reviewing and personalising AI output as important, rather than using it unchanged?",
 "opts":["Because you remain accountable for the accuracy and fitness of what you send",
         "Because AI output is always factually wrong in every single case without exception",
         "Because using unchanged AI output is against the law in most professional settings",
         "Because the AI model retains ownership of any output that it generates for you"],
 "ans":0,
 "exp":"This ties Domain 4 to Domains 5 and 8, since the syllabus states plainly that the user rather than the AI remains accountable. Reviewing and personalising output is how that accountability is discharged in practice.",
 "why":["Correct. Accountability sits with the human, so review and personalisation are obligations rather than courtesies.",
        "AI output is often accurate, but accuracy cannot be assumed, which is a different and more useful point.",
        "The syllabus explicitly excludes legal interpretation, so a legal prohibition is not the syllabus position.",
        "Ownership questions sit outside the syllabus scope, and the real driver is professional accountability."]},
]
